name: GitOps-Flow
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and Push
        run: |
          # Tagging with the unique Git Commit Hash
          docker build -t ${{ secrets.DOCKER_USER }}/rps-game:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USER }}/rps-game:${{ github.sha }}

      - name: Update GitOps Manifest
        run: |
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/${{ github.repository_owner }}/rps-gitops.git
          cd rps-gitops
          # This line finds the image field and swaps it with the new version
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USER }}/rps-game:${{ github.sha }}|g" deployment.yaml
          git config user.name "GitOps Bot"
          git config user.email "bot@gitops.com"
          git add .
          git commit -m "Deploy version ${{ github.sha }}"
          git push
